#encoding: utf-8
development:
  adapter: mysql2
  database: city_development
  username: root
  password:
  host: localhost
  encoding: utf8
test:
  adapter: mysql2
  database: city_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: city_production
  username: root
  password: 
  host: localhost
  encoding: utf8
