development:
  adapter: mysql
  database: city_development
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  database: city_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  database: city_production
  username: root
  password: 
  host: localhost